jobs:
  include:
    - stage: "Test"
      name: "Use custom image test1"
      vm:
        use:
          name: 2705-image
      script:
        - echo "Using ..."
    - stage: "Test"
      name: "Use custom image test2"
      vm:
        use:
          name: 2705-image8 #non existing image
      script:
        - echo "Using ..."
