jobs:
  include:
    - stage: create image
      os: linux
      dist: focal
      vm:
        create:
          name: 2705-image3
      before_install:
        - sudo apt-get -y install libxml2-dev
      addons:
        apt:
          update: true

    - stage: use custom image
      vm:
        use: 2705-image #existing image
      script:
        - echo "Running job with custom image"
